---
# handlers file for slurm-controller
- name: Restart slurmdbd
  ansible.builtin.service:
    name: slurmdbd
    state: restarted
  when: not slurm_disable_restart

- name: Restart slurmctld
  ansible.builtin.service:
    name: slurmctld
    state: restarted
  when: not slurm_disable_restart

- name: Check slurmctld actually restarted
  ansible.builtin.wait_for:
    port: 6817
    delay: 10
  run_once: true
  when: not slurm_disable_restart
  listen: Restart slurmctld

- name: Restart slurmd
  ansible.builtin.service:
    name: slurmd
    state: restarted
  when: not ansible_is_chroot and not slurm_disable_restart

- name: Reload firewalld
  ansible.builtin.service:
    name: firewalld
    state: reloaded
  become: true
