---
- name: Create temporary source dir
  ansible.builtin.file:
    state: directory
    path: "{{ slurm_tmpdir }}"
    mode: "0777"
  when: install_slurm
  tags:
    - slurm
    - slurm_install_controller
    - slurm_install_slurmd
    - slurm_install_restd

- ansible.builtin.include_tasks: "jwt.yaml"
  when: slurm_enable_restd and install_slurm
  tags:
    always

- ansible.builtin.include_tasks: "pmix.yaml"
  when: slurm_enable_pmix and install_slurm
  tags:
    always

- name: Download slurm
  get_url:
    url: "https://github.com/SchedMD/slurm/archive/refs/\
          tags/slurm-{{slurm_download_version}}.zip"
    dest: "{{slurm_tmpdir}}/slurm-{{slurm_download_version}}.zip"
  register: slurm_source
  when: install_slurm
  tags:
    - slurm
    - slurm_install_controller
    - slurm_install_slurmd

- name: extract slurm archive
  unarchive:
    copy: false
    dest: "{{slurm_tmpdir}}"
    src: "{{slurm_source.dest}}"
  when: slurm_source.changed
  register: slurm_source_unpack
  tags:
    - slurm
    - slurm_install_controller
    - slurm_install_slurmd


- name: Configure slurm
  command: "./configure --prefix=/{{slurm_install_directory}} --sysconfdir=/etc/slurm \
            --localstatedir=/var --runstatedir=/run {% if slurm_enable_restd %}--with-jwt={{slurm_install_directory}}{% endif %}\
            {% if slurm_enable_pmix %} --with-pmix={{slurm_install_directory}}{% endif %}"
  args:
    chdir: "{{slurm_tmpdir}}/slurm-slurm-{{slurm_download_version}}"
  when: slurm_source_unpack is changed
  register: slurm_configure
  tags:
    - slurm
    - slurm_install_controller
    - slurm_install_slurmd

- name: Install slurm
  shell: "make -j {{slurm_build_jobs}} && make install"
  args:
    chdir: "{{slurm_tmpdir}}/slurm-slurm-{{slurm_download_version}}"
  when: slurm_configure is changed
  tags:
    - slurm
    - slurm_install_controller
    - slurm_install_slurmd

- name: Install pmi
  shell: "make -j {{slurm_build_jobs}} && make install"
  args:
    chdir: "{{slurm_tmpdir}}/slurm-slurm-{{slurm_download_version}}/contribs/pmi2"
  when: slurm_configure is changed
  tags:
    - slurm
    - slurm_install_controller
    - slurm_install_slurmd

- name: Install slurm pam adopt
  shell: "make && make install"
  args:
    chdir: "{{slurm_tmpdir}}/slurm-slurm-{{slurm_download_version}}/contribs/pam_slurm_adopt/"
  when: slurm_configure is changed 
  tags:
    - slurm
    - slurm_install_slurmd

# TODO: Cleanup tmp spaces
#- name: Clean up tmp space
  #ansible.builtin.file:
    #state: absent
    #path: "{{slurm_tmpdir}}"
