- name: Start mariadb
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: true
  tags:
    - slurm
    - slurm_install_controller

- name: Create database user slurm
  community.mysql.mysql_user:
    name: slurm
    encrypted: true
    priv: '*.*:ALL'
    state: present
    login_unix_socket: /var/lib/mysql/mysql.sock
  tags:
    - slurm
    - slurm_install_controller

- name: Make local tempfile for slurmdbd.conf templating # ensures simultaneous runs don't clobber each other
  ansible.builtin.tempfile:
  register: _slurmdbd_conf_tmpfile
  delegate_to: localhost
  changed_when: false # so molecule doesn't fail
  tags:
    - slurm
    - slurm_configure

- name: Template slurmdbd configuration file
  ansible.builtin.template:
    src: templates/slurmdbd.conf.j2
    dest: "{{ _slurmdbd_conf_tmpfile.path }}"
    lstrip_blocks: true
    mode: "0600"
  delegate_to: localhost
  changed_when: false # so molecule doesn't fail
  tags:
    - slurm
    - slurm_configure

- name: Customize slurmdbd.conf
  community.general.ini_file:
    path: "{{ _slurmdbd_conf_tmpfile.path }}"
    option: "{{ item.key }}"
    section: ''
    value: "{{ (item.value | join(',')) if (item.value is sequence and item.value is not string) else item.value }}"
    no_extra_spaces: true
    create: false
    mode: "0644"
  loop: "{{ slurmdbd_conf_extra | dict2items }}"
  delegate_to: localhost
  changed_when: false # so molecule doesn't fail
  tags:
    - slurm
    - slurm_configure

- name: Create slurmdbd.conf
  ansible.builtin.copy:
    src: "{{ _slurmdbd_conf_tmpfile.path }}"
    dest: /etc/slurm/slurmdbd.conf
    owner: slurm
    group: slurm
    mode: "0600"
  notify:
    - Restart slurmdbd
  tags:
    - slurm
    - slurm_configure

- name: Remove local tempfile for slurmdbd.conf templating
  ansible.builtin.file:
    path: "{{ _slurmdbd_conf_tmpfile.path }}"
    state: absent
  when: _slurmdbd_conf_tmpfile.path is defined
  delegate_to: localhost
  changed_when: false # so molecule doesn't fail
  become: false
  tags:
    - slurm
    - slurm_configure


- name: Create slurmdbd service file
  ansible.builtin.template:
    src: templates/slurmdbd.service.j2
    dest: /etc/systemd/system/slurmdbd.service
    owner: root
    group: root
    mode: "0644"
  tags:
    - slurm
    - slurm_install_controller

- name: Start slurmdbd service
  ansible.builtin.service:
    name: slurmdbd
    state: started
    enabled: true
  tags:
    - slurm
    - slurm_install_controller
